const BASE_URL_DEVELOPMENT = 'https://localhost:7097/api/';

const ENTITIES = {
    CONTACT: 'Contact/',
    MESSAGE: 'Message/',
    OBJECTIVE: 'Objective/',
    PLANNING: 'Planning/',
    PROJECT: 'Project/',
    SPRINT: 'Sprint/',
    TASK: 'Task/',
    TEAM: 'Team/',
    TEAM_ROLE: 'TeamRole/',
    USER: 'User/',
    USER_MESSAGE_CONTACT: 'UserMessageContact/',
    USER_TEAM_TEAM_ROLE: 'UserTeamTeamRole/'
};

const CRUD = {
    CREATE: "Create",
    UPDATE: "Update",
    GET_ALL: "GetAll",
    GET: "Get",
    DELETE: "Delete",
};

const CONTACT = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.CONTACT}${CRUD.CREATE}Contact`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.CONTACT}${CRUD.UPDATE}Contact`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.CONTACT}${CRUD.GET_ALL}Contacts`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.CONTACT}${CRUD.GET}Contact`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.CONTACT}${CRUD.DELETE}Contact`
};

const MESSAGE = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.MESSAGE}${CRUD.CREATE}Message`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.MESSAGE}${CRUD.UPDATE}Message`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.MESSAGE}${CRUD.GET_ALL}Messages`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.MESSAGE}${CRUD.GET}Message`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.MESSAGE}${CRUD.DELETE}Message`
};

const OBJECTIVE = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.OBJECTIVE}${CRUD.CREATE}Objective`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.OBJECTIVE}${CRUD.UPDATE} Objective`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.OBJECTIVE}${CRUD.GET_ALL}Objectives`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.OBJECTIVE}${CRUD.GET}Objective`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.OBJECTIVE}${CRUD.DELETE}Objective`
};

const PLANNING = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}Planning`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}Planning`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}Plannings`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}Planning`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}Planning`
};

const PROJECT = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}Project`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}Project`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}Projects`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}Project`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}Project`
};

const SPRINT = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}Sprint`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}Sprint`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}Sprints`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}Sprint`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}Sprint`
};

const TASK = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}Task`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}Task`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}Tasks`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}Task`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}Task`
};

const TEAM = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}Team`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}Team`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}Teams`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}Team`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}Team`
};

const TEAM_ROLE = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}TeamRole`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}TeamRole`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}TeamRoles`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}TeamRole`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}TeamRole`
};

const USER = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}User`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}User`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}Users`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}User`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}User`
};

const USER_MESSAGE_CONTACT = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}UserMessageContact`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}UserMessageContact`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}UserMessageContacts`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}UserMessageContact`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}UserMessageContact`
};

const USER_TEAM_TEAM_ROLE = {
    CREATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.CREATE}UserTeamTeamRole`,
    UPDATE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.UPDATE}UserTeamTeamRole`,
    GET_ALL: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET_ALL}UserTeamTeamRoles`,
    GET: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.GET}UserTeamTeamRole`,
    DELETE: `${BASE_URL_DEVELOPMENT}${ENTITIES.PLANNING}${CRUD.DELETE}UserTeamTeamRole`
};

export {
    CONTACT, 
    MESSAGE, 
    OBJECTIVE, 
    PLANNING, 
    PROJECT, 
    SPRINT, 
    TASK, 
    TEAM, 
    TEAM_ROLE, 
    USER, 
    USER_MESSAGE_CONTACT, 
    USER_TEAM_TEAM_ROLE
};